# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('none', models.IntegerField(default=-1000)),
                ('name', models.CharField(blank=True, max_length=122100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('none', models.IntegerField(default=-1000)),
                ('name', models.CharField(blank=True, max_length=122100, null=True)),
                ('model', models.CharField(blank=True, max_length=122100, null=True)),
                ('cc', models.CharField(blank=True, max_length=122100, null=True)),
                ('name1', models.CharField(blank=True, max_length=122100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('none', models.IntegerField(default=-1000)),
                ('name', models.CharField(blank=True, max_length=122100, null=True)),
                ('idv', models.CharField(blank=True, max_length=122100, null=True)),
                ('cover', models.CharField(blank=True, max_length=122100, null=True)),
            ],
        ),
    ]
