# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_auto_20181007_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('none', models.IntegerField(default=-1000)),
                ('loct', models.CharField(blank=True, max_length=122100, null=True)),
                ('loct_code', models.CharField(blank=True, max_length=122100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='make',
            name='modelc',
            field=models.CharField(blank=True, max_length=122100, null=True),
        ),
        migrations.AddField(
            model_name='make',
            name='namec',
            field=models.CharField(blank=True, max_length=122100, null=True),
        ),
    ]
