# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-23 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0003_auto_20181008_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='rto',
            name='city_code',
            field=models.CharField(blank=True, max_length=122100, null=True),
        ),
        migrations.AddField(
            model_name='rto',
            name='state_code',
            field=models.CharField(blank=True, max_length=122100, null=True),
        ),
    ]
