# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example_app', '0004_auto_20181023_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='text',
            field=models.CharField(blank=True, max_length=122100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
