# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 10:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workfile',
            name='file',
        ),
        migrations.AddField(
            model_name='workfile',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
